### ISSUE TITLE
Unable to install odevio in windows 10

### ISSUE THREAD

**Issue by TuupleMasterAndroid** [Odevio/Odevio-CLI#48]
Unable to install odevio in windows 10

`C:\>pip install odevio

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'
`

**Comment by maxcmoi89** [comment]
It's because PIP isn't properly installed on your computer. PIP is the python package manager. You can either reinstall pip or you can download our desktop client which should be easier to use if you are not familiar with CLI interfaces. You can download the desktop client from our website : https://www.odevio.com/.
